### ISSUE TITLE
modularize languagetool client and update to tinyMCE 4.x

### ISSUE THREAD

**Issue by ceilino** [languagetool-org/languagetool-website#12]
Hi there,

I have tried integrating the editor, but its really actually quite complicated. 

I ultimately want to create an open source angular directive for languagetool. I find languagetool quite nice.
I have in the meantime created an temporal repository at https://github.com/ControlExpert/angular-languagetool

There is an existent angular wrapper directive for tinymce (ui-tinymce) but it only works with tinyMCE 4.x. I myself don't think is yet robust. (just looking at its codestyle and based on my prototype experience)

The current difficulties i'm facing and see are:
- The actual dependencies for the javascript language tool are not all modular and clear. (JS partially, CSS, HTML)
- the languagetool library is based on the AtD plugin which is no longer supported (since 2 years, since they switched to offer their own solution).
- AtD itself is based on tinyMCE 3.5.6 API.  tinyMCE 3.x is no longer supported nor improved. 
- It seems not possible to use the languagetool in multiple places at the same time. (tinyMCE 4.x covers this scenario)
- ui-tinymce won't integrate to languagetool (due to API changes and deep AtD dependencies) 
- languagetool seems to heavily rely on some HTML FORM information and specific html structures.
- tinyMCE 3.5 rely on creating an iframe. Which is in itself a complex HTML structure.
- Typically a good quality angular directive, can be used at any place. So the code&html should be modular and loosely decoupled. So this does not play too good with the current languagetool.
- Very complicated to use the languagetool library in modern web projects, its not available in public repositories.
  *\* Not possible include in gulp/grunt workflows that use bower/npm for 3rd party dependencies
  *\* Not possible include in gulp/grunt workflows that compress all 3rd party dependencies into a single file.

So what I think would good steps to bring languagetool to the next level:
- Create a dedicated project only for the JS/CSS library of languagetool
  *\* CSS should be clean and modular.
  *\* This would be framework agnostic, so potentially, assuming that languagetool is very well modularized, it could be reused by powerful frameworks like Angular, React, etc.
  *\* OPTIONAL Add a modern gulp-based build workflow. That would also bring automated best practices to the code. (like automated code style checks, JSCS and JSHint)
- Create a bower package so that it is available in the bower public repository.
- Remove dependence to old tinyMCE 3.x API and upgrade to use TinyMCE 4.2 API. That would enable multiple editors on a page plus lots of big improvements.
  *\* TinyMCE 4.x offers spellchecking plugin, perhaps this can replace what AtD was doing.
- Create a clean angular directive that brings the most potential of languagetool. I image that there are certain features that are in the scope of tinyMCE API, and could be covered by the angular directive.
  *\* These directive could be in a separate directory or not.
  *\* Angular is the leading javascript MVC framework since some years. (see analysis graph at http://www.infoq.com/research/javascript-frameworks-2015)

Relevant  links:
- TinyMCE 4.x spellchecker config: http://www.tinymce.com/wiki.php/Configuration:spellchecker_rpc_url
- http://www.tinymce.com/wiki.php/Tutorial:Migration_guide_from_3.x
- TinyMCE spellchecker plugin:  https://github.com/tinymce/tinymce/tree/master/js/tinymce/plugins/spellchecker/classes
- https://github.com/angular-ui/ui-tinymce

**Comment by ceilino** [comment]
An example of spellchecker integration is at:

http://tinymcespellcheck.com/nanospell/plugin.js

its called Nanospell, a spellchecker plugin for tinyMCE 4.x

**Comment by danielnaber** [comment]
Hi, it's great that someone is working on this. Do you have a roadmap? I'm asking because there are problems with MSIE (see #13) and I'm not sure how much time we should spend on them if you have a total rewrite anyway...

**Comment by igorlino** [comment]
I just wanted to get LanguageTool to work with angular. The prototype was a total disaster.
It killed the angular application. (So I had to use the axe)
Total rewrite was out of question, since we need a solution yesterday. At the moment we use the chrome spellchecker, but its just a workaround.

An example of a total rewrite, is to look at how nano spellchecker does it:

http://tinymcespellcheck.com/nanospell/plugin.js

From the website: http://tinymcespellcheck.com/

I could of course create a pet-project, (like my other open source projects), but I need support and cannot/would not do it alone. Specially with dealing with the backend integration.

So if there is support, I'm think I could spend sometime with a rewrite.

**Comment by danielnaber** [comment]
I can help with testing and help with LanguageTool-specific issues, but I'm not very good at JavaScript.

**Comment by ceilino** [comment]
Perhaps there is another JS dev that may help. I have asked some days ago, no feedback so far.

**Comment by eduardofcbg** [comment]
This issue was open back in 2015, is there an update on this? Or should we just stick to tinyMCE 3?

**Comment by igorlino** [comment]
I had very good intentions back then, as languagetool is very powerful, but there was simply no ROI nor I had enough spare time for that kind of undertaking.

**Comment by KnowZero** [comment]
I am trying to combine TinyMCE 4 + LanguageTool. It works but it is in alpha so expect a lot of bugs here and there. Though not to sure about it being angular.

https://github.com/KnowZero/tinymce4-languagetool

The problem I found with many other spellchecker plugins is that they do not factor in multi-word grammar. Which gets even worse when you have same exact word or phrase in different context. So I decided to make my own method of handling things.

To make languagetool operate better for this kind of applications, I gave each object a unique id. Then I pass that unique id to languagetool. Afterwards I took the combination of offset and unique id to figure out where it belongs. Then I take the size of the HTML element and compare them to the offset of the Text element.

This way I can spellcheck and grammar check things that across multiple nodes.

**Comment by danielnaber** [comment]
@KnowZero Are you still working on this? What is the current status?

**Comment by KnowZero** [comment]
@danielnaber sorry for the really really late response. I check email really rarely and I checked github while not logged in so didn't see the post here (since it wasn't under my profile)

Yes, I am still working on this. As I mentioned in the email, I need to get my other projects out of the way so I can fully focus on it. Particularly I want to make it more modular to include Immutable based clients like ProseMirror and the like.

Again, sorry for the REALLY late response.

**Comment by danielnaber** [comment]
Closing old issues, as this repo is not used anymore

**Comment by igorlino** [comment]
RIP   :)

**Comment by KnowZero** [comment]
I don't know if to say its dead. I mean it is still on my todo list as I plan to integrate it into my project for work. Just higher priority stuff got in the way such as GDPR and other regulatory compliances, and now we have the whole COVID thing.

But that is for the complete rewrite. Which would remove dependence on jquery and make it work outside of TinyMCE only. I did some work on that already by splitting up the logic with the tinymce portions.

That said, I still provide support for people for the old version if something breaks(though it might take a few weeks). And so far only issues people have reported were unique cases of compatibility with other software or setup issues. And I have fixed all those.

**So to put it simple, it's not RIP, it's kinda already done.** At the very least I have not had any new bug reports for over 3 years and most recent one that I got seems to have be a setup issue rather than any error. So that either means no one is using it or its working fine with no issues.

The reason why I still call it Alpha/Expiremental is because I can't guarantee how much testing it has gotten. I was hoping to do a rewrite, than implement it on my own end. Then I would call it Beta, and after running it for a year I would call it stable.

So if all you want is TinyMCE 4.X support, you are free to use it. I don't use angular myself but someone who had an issue did and it worked for them.

The only thing I am not doing for the old version is adding any new features. But if you run into any bugs I'll still help fix them (though it might take a week or 2).

Once I finish the major projects in the pipeline, the rewrite is my first priority out of the medium projects.
