### ISSUE TITLE
"Invalid argument" with MS Edge and IE

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool-website#13]
Edge doesn't work with the check form on languagetool.org as it throws an error somewhere in the tinyMCE code.

**Comment by danielnaber** [comment]
![ie](https://cloud.githubusercontent.com/assets/857004/11090157/daac6a66-886f-11e5-883a-20e5e78ef706.png)

Screenshot on IE10

**Comment by AlphawolfWMP** [comment]
Hi Daniel, Oliver from rechtschreibpruefung24.de here.

The reason why it also affects IE10 and other versions of IE10 may be that MS implemented (parts of) the Edge rendering engine into older versions of IE as well. That's why they "behave" different suddenly even though the used javascripts never changed ever since.

As for the problem: Please remove or comment out the `directionality: 'auto'` part in the `tinyMCE.init` call. I'm not yet sure why, but obviously the `'auto'` value caused the issue. Setting `directionality` to specifically `'ltr'` or `'rtl'` does work too, so `'auto'` seems to have a problem here.

**Comment by danielnaber** [comment]
Thanks, setting the direction manually fixes the issue.

**Comment by guptadharamveer53** [comment]
![image](https://user-images.githubusercontent.com/16339868/27421534-77bf2d90-5748-11e7-84a4-c32766556988.png)

**Comment by danielnaber** [comment]
@guptadharamveer53 how is that index.html related to LanguageTool?
